### ISSUE TITLE
rail removal code tries to index a nil value when destroying some rails

### ISSUE THREAD

**Issue by jvantuyl** [Hermios/RailPowerSystem#1]
Cargo Ships (v0.0.51) seems to make magic "rails" to create its waterways.

In RailPowerSystem 0.4.2, destroying a waterway generates an error.  In this case, I had removed the rail via BlueBuild, but I've verified that it happens just removing it by hand, too.  It also seems someone else was hitting the same bug removing old-style rails on the mod portal [here](https://mods.factorio.com/mod/RailPowerSystem/discussion/5e9f2d34c60fdc000ee7ff34).

Text of the error message was as follows:
```
The mod Bluebuild (1.2.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Bluebuild::on_tick (ID 0)
The mod RailPowerSystem (0.4.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RailPowerSystem::on_pre_player_mined_item (ID 11)
__RailPowerSystem__/methods/globalEvents.lua:64: attempt to index field '?' (a nil value)
stack traceback:
	__RailPowerSystem__/methods/globalEvents.lua:64: in function 'OnRemoved'
	__HermiosLibs__/controlLib.lua:92: in function <__HermiosLibs__/controlLib.lua:86>
stack traceback:
	__Bluebuild__/control.lua:185: in function 'bluedemo'
	__Bluebuild__/control.lua:60: in function 'bluecheck'
	__Bluebuild__/control.lua:31: in function 'playerloop'
	__Bluebuild__/control.lua:309: in function <__Bluebuild__/control.lua:308>
stack traceback:
	[C]: in function 'mine_entity'
	__Bluebuild__/control.lua:185: in function 'bluedemo'
	__Bluebuild__/control.lua:60: in function 'bluecheck'
	__Bluebuild__/control.lua:31: in function 'playerloop'
	__Bluebuild__/control.lua:309: in function <__Bluebuild__/control.lua:308>
```

I was able to fix it by changing the `railEntity.OnRemoved` function in `methods/globalEvents.lua` to check for `nil` on the rail list before trying to remove it.  I could not find the current version here on GitHub, so I'm filing this as an issue instead of a pull request.

Code fix that worked for me was this:
```lua
railEntity.OnRemoved=function(entity)
        if listRails[entity.unit_number] then
                listRails[entity.unit_number]:remove()
        end
end
```

Thanks for a wonderful mod.  👍

**Comment by Cordina90** [comment]
Made a similar fix for the error on line 33 (connector poles).
replace lines 32-37:
```
connectorEntity.OnRemoved=function(entity)  
    local connectedRail=listRailPoleConnectors[entity.unit_number]:remove()
    if connectedRail then
        table.insert(listConnectionsToClean,connectedRail)
    end
end
```

with:

```
connectorEntity.OnRemoved=function(entity)  
    if listRailPoleConnectors[entity.unit_number] then
        local connectedRail=listRailPoleConnectors[entity.unit_number]:remove()
        if connectedRail then
            table.insert(listConnectionsToClean,connectedRail)
        end
    end
end
```

This allows the connector poles to be removed. Don't know if this causes problems elsewhere in the mod (haven't noticed yet...)

**Comment by jvantuyl** [comment]
Did this ever get fixed?

**Comment by Hermios** [comment]
Hey
As weird as it sounds... I'm on it! But it won't be before September, probably later! I am redesigning the code!(was non sense). And this will be for the last version
