### ISSUE TITLE
Deleting Gun or Laser Turrets Causes Crash

### ISSUE THREAD

**Issue by Ydamiano** [Hermios/RailPowerSystem#28]
*Error Message*
The mod RailPowerSystem (1.0.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RailPowerSystem::on_entity_destroyed (ID 160)
__RailPowerSystem__/control.lua:43: attempt to index local 'destroyed_item_data' (a nil value)
stack traceback:
	__RailPowerSystem__/control.lua:43: in function 'f'
	__Hermios_Framework__/control-libs.lua:20: in function <__Hermios_Framework__/control-libs.lua:13>

If I try to delete a gun turret OR laser turret next to rails & medium electric pole, the above crash occurs.

**Steps to reproduce**
1.  I have some established rail lines and power network through my oil field.  It was my very first oil field and is a mess, \
2.  50 hours later I discovered mods!
3.  Returning to this area to revamp the transportation and power grids in the area but that necessitates removing the existing light, pumpjack, medium electric line, and gun turret.
4. I was able to place a gun turret with piercing ammo rounds at another location next to power lines and rails.
5. Now tried removing any gun turret on the continent and still get the same issue.

**Expected Behavior**
The game crashes and gives the above stated error message.

**Attachments**
![20240430044259_1](https://github.com/Hermios/RailPowerSystem/assets/168539862/210163f2-04ec-4c62-9c3d-76b8358c76c0)
![20240430044327_1](https://github.com/Hermios/RailPowerSystem/assets/168539862/2f73e6c0-6da4-4b11-9bde-874bc9be6243)
![20240430044446_1](https://github.com/Hermios/RailPowerSystem/assets/168539862/5aadcfe0-fd3e-45d3-8b5e-2084a3b7c3e5)
![20240430044456_1](https://github.com/Hermios/RailPowerSystem/assets/168539862/db4ad039-c7cf-4a89-823c-8db5a5da17ca)

**Additional Information**
I haven't started building any items specific to your mods yet, since I just installed them yesterday.  I do have several other mods installed but nothing that modifies gun turrets.  I have seen three unrelated crashes from this mod just interacting with random rails or power lines in undeveloped areas.  But I have noticed no discernible pattern to these, whereas the gun turret issue consistently occurs 100% of the time for me.  Thanks for your time.

**Comment by Hermios** [comment]
Hei @Ydamiano  Thanks for the very complete message. I will look into it. Can you confirm that rails are from my mod? (Or not??)
From the picture, I would say those are normal rails, but your text let me believe they are power rails.
Thanks

**Comment by Hermios** [comment]
@Ydamiano Many thanks for the very complete message. I think I found the issue, will generate a fix. But I cannot test it, because the problem is connected to one of the mods you used (But I cannot tell which one).
Thanks

**Comment by Ydamiano** [comment]
Tomorrow I will re-enable your mod and test the fix you made.  I'll let you
know how it goes.
