### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Vasyanator** [Hermios/RailPowerSystem#33]
**Describe the bug**
1. error in the name of the fuel in the electric train (screenshot below).

**Steps to reproduce**
1. I don't know if it's related, but my interface in Factorio is in Russian.

**Expected behavior**
1. "fuel" has an electric icon and a normal name.

**Screenshots/Videos (If you have any)**

![image](https://github.com/Hermios/RailPowerSystem/assets/135327897/2f1260db-adb8-4229-a2d0-88d56c2e9507)

**Additional Information**
I would be very grateful if you could fix these problems.

**Comment by Hermios** [comment]
I modified this error to divide in 3, one issue per error (Easier to follow).
