### ISSUE TITLE
[bug] Second electric locomotive has no fuel

### ISSUE THREAD

**Issue by Vasyanator** [Hermios/RailPowerSystem#40]
**Describe the bug**
If there are 2 electric locomotives in one train, the second one does not work.

**Steps to reproduce**
Create a train with two locomotives in the same direction and try to go.

**Expected behavior**
Both locomotives will be running.

**Screenshots/Videos (If you have any)**

![image](https://github.com/Hermios/RailPowerSystem/assets/135327897/b17ddcad-431c-4930-9739-a9aeb5d90ee5)

**Additional Information**

**Comment by Hermios** [comment]
Duplicate from #38
