### ISSUE TITLE
[feature request] Compatible with Automatic Train Fuel Stop mod

### ISSUE THREAD

**Issue by Vasyanator** [Hermios/RailPowerSystem#41]
I suggest adding basic compatibility with the Automatic Train Fuel Stop mod (https://github.com/magu5026/FuelTrainStop) by making it ignore electric locomotives. Now this mod is constantly trying to direct electric locomotives to the Fuel Stop.

**Comment by Hermios** [comment]
I have to reject this issue, because the behavior is controlled by the other mod. You should make this request to the owner of this mod
