### ISSUE TITLE
[Feature] Customizable locomotive speed and power.

### ISSUE THREAD

**Issue by Vasyanator** [Hermios/RailPowerSystem#43]
I suggest adding a speed and power setting for each locomotive. You can either use sliders in GUI or special modules. Of course, the higher the speed and power, the higher the electricity consumption. It is also possible to add technologies that increase the maximum available speed and power of electric locomotives.

**Comment by Hermios** [comment]
Thanks the idea. However, I am quite busy now, and  it's not a need for me, considering my way of playing, so I won't do it, sorry. However, this could be an extra mod, it could be even applied to any kind of loco.

**Comment by Hermios** [comment]
No priority
